name: Conditional env variable

on: workflow_dispatch

env:
  DAY_OF_WEEK: Monday

jobs:
  greeting_job:
    runs-on: ubuntu-latest
    environment: dev
    env:
      Greeting: Hello
    steps:
      - name: "Print Env"
        run: "echo host:$ENV_GIT_HOST /"
        env:
          First_Name: Mona
